### ISSUE TITLE
Can you add an option to just copy URL?

### ISSUE THREAD

**Issue by Gitoffthelawn** [takedajs/TitleUrlCopy#1]
Useful extension, thanks!

Can you add an option to just copy the URL?

**Comment by takedajs** [comment]
@Gitoffthelawn 
Thank you for the issue!
What kind of implementation method should I use? If you specify only the URL in the setting, when you press command + c, do you copy the URL?

**Comment by Gitoffthelawn** [comment]
You're welcome!  Thank you for the extension! :)

Yes, if you specify only the URL, when you press command + c, just copy the URL without any title.

**Comment by takedajs** [comment]
@Gitoffthelawn 
> Yes, if you specify only the URL, when you press command + c, just copy the URL without any title.

Sorry I made you wait ! I corresponded to this. 
https://addons.mozilla.org/ja/firefox/addon/titleurlcopy/

**Comment by Gitoffthelawn** [comment]
No problem!  Thank you! :-)
