### ISSUE TITLE
Feature Request: Allow custom formatting of output

### ISSUE THREAD

**Issue by damengilland** [takedajs/TitleUrlCopy#13]
Markdown is OK... `[Hacker News](https://news.ycombinator.com/news)` but what I want is more like `* Hacker News || https://news.ycombinator.com/news` for faster copy and paste into emails -- everyone is going to want their own thing.  Would be great if we could customize the output.

**Comment by takedajs** [comment]
@damengilland Thanks for the issue. I am sorry, but I do not currently plan to implement that.
