### ISSUE TITLE
Add command + shift + c to copy ALL tabs

### ISSUE THREAD

**Issue by Gitoffthelawn** [takedajs/TitleUrlCopy#3]
Can you add the ability to copy the urls of all tabs with command + shift + c ?

**Comment by takedajs** [comment]
Sorry, I have no plan to respond m(_ _)m

**Comment by takedajs** [comment]
@Gitoffthelawn I'd like to ask for your reference, is this not the case?
When you press command + shift + c, you get the title and URL of all tabs.

example
```
Add command + shift + c to copy ALL tabs · Issue #3 · takedajs/TitleUrlCopy
https://github.com/takedajs/TitleUrlCopy/issues/3

Add command + shift + c to copy ALL tabs · Issue #3 · takedajs/TitleUrlCopy
https://github.com/takedajs/TitleUrlCopy/issues/3

Add command + shift + c to copy ALL tabs · Issue #3 · takedajs/TitleUrlCopy
https://github.com/takedajs/TitleUrlCopy/issues/3
```

**Comment by takedajs** [comment]
@Gitoffthelawn 
>Can you add the ability to copy the urls of all tabs with command + shift + c ?

Sorry I made you wait ! I corresponded to this.
https://addons.mozilla.org/ja/firefox/addon/titleurlcopy/

I tried implementing with command + shift + c but it did not work well. So we implemented it with command + c + x .

**Comment by Gitoffthelawn** [comment]
Strange that command + shift + c would work... perhaps it's reserved.

So is it command + c, then x?

**Comment by takedajs** [comment]
That's right. When pressing command+ shift + c, the following events do not work so you can not copy to the clipboard.
```
document.addEventListener('copy', function(e){
```
So I specified x instead of shift.
