### ISSUE TITLE
Add keyboard/shortcut for copy all Tabs.

### ISSUE THREAD

**Issue by aramiskenderian** [takedajs/TitleUrlCopy#9]
Is it possible to extend this extension to copy all Title/URLs for all open tabs on current/all open Windows?
That would be an awesome feature.
Thanks for the efficient and excellent add-on.

**Comment by takedajs** [comment]
@aramiskenderian 
Issues thanks ! You can copy all the tab information.
When you want to acquire all tabs: command+c+x (mac) or ctrl+c+x (win).
Please see the method on the site listed on the site.

```
TitleUrlCopy
https://addons.mozilla.org/ja/firefox/addon/titleurlcopy/
```

**Comment by aramiskenderian** [comment]
Somehow I missed that.
Thank you very much.
